### PR TITLE
fix: after git checkout of new branch, first git pull needed on this …

### PR DESCRIPTION
**Pull request by k0nsti**
…branch before use entries

Hallo Markus,
kannst du dir bitte die Änderung angucken, das git pull auf dem branch findet erst nachdem die entries zurückgegeben wurden statt. Falls du mit der Änderung einverstanden bist, bitte neues Package bauen ))) 
Danke

### CODE REVIEW

**Comment by arlac77** [comment]
I do not understands the problem.
What is the none working workflow?
Maybe the remote has some commits and the local repo needs to be updated?

**Comment by k0nsti** [comment]
yes, if remote somethink has changed, local branch has still old local entry after git checkout, but (dno-util) needs the new changed entry from remote. Initialize after switching to another branch happens later as return of a branch.entries

**Comment by approximate** [comment]
Hi Markus.

The problem is that in case the local repo already existed (as opposed to being cloned from scratch), then switching to another local branch can potentially miss the latest commits that already exist in the corresponding remote branch. In general, git only pulls changes for the currently active branch, so even if we did "git pull" explicitly before, but then switched to another branch that is tracking the remote branch, we need to do "git pull" again to be sure we received all the commits from the remote branch.

In case where the local repo does not exist yet, this problem doesn't come up: a new clone is made, and cloning automatically takes care of the entire DAG of commits, meaning that all branches are up-to-date by the time the cloning finishes. As explained above, if "git clone" is not done, there's a possibility that some branches are out-of-date (i.e. the remote repo has newer commits), so each time we switch to another branch, we also have to do "git pull" to bring our local branch up-to-date.

**Comment by arlac77** [comment]
@k0nsti, @approximate  did you try bitbucket-repository-provider ?

**Comment by k0nsti** [comment]
we haven`t

**Pull request merged**
